spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/balancetogether
      ?useUnicode=true
      &characterEncoding=utf8mb4
      &connectionCollation=utf8mb4_general_ci
      &serverTimezone=UTC
    username: root
    password: 123qwe
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
